FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG PUBLIC_API_BASE=http://localhost:3000
ARG PUBLIC_MIDTRANS_CLIENT_KEY=
ARG PUBLIC_MIDTRANS_IS_PRODUCTION=false
ARG PUBLIC_WA_NUMBER=
ARG PUBLIC_TURNSTILE_SITE_KEY=
ENV PUBLIC_API_BASE=$PUBLIC_API_BASE
ENV PUBLIC_MIDTRANS_CLIENT_KEY=$PUBLIC_MIDTRANS_CLIENT_KEY
ENV PUBLIC_MIDTRANS_IS_PRODUCTION=$PUBLIC_MIDTRANS_IS_PRODUCTION
ENV PUBLIC_WA_NUMBER=$PUBLIC_WA_NUMBER
ENV PUBLIC_TURNSTILE_SITE_KEY=$PUBLIC_TURNSTILE_SITE_KEY
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 4321
CMD ["node", "dist/server/entry.mjs"]
